# Generated by Django 6.0.5 on 2026-05-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', '0-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('date_of_birth', models.CharField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('User_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='accounts.userprofile')),
            ],
        ),
    ]
