# Generated by Django 6.0.5 on 2026-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='experience_year',
            new_name='experience_years',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='User_profile',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
